# Generated by Django 4.2 on 2023-04-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbak_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunbak_crawl_datamodel',
            name='detailURL',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
