# Generated by Django 4.2 on 2023-04-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbak_crawler', '0002_sunbak_crawl_datamodel_detailurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='connectionTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('boardType', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='sunbak_crawl_datamodel',
            name='detailURL',
            field=models.CharField(max_length=255),
        ),
    ]
