# Generated by Django 4.2 on 2023-05-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbak_crawler', '0003_connectiontimemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunbak_crawl_datamodel',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
