# Generated by Django 4.2 on 2023-05-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbak_crawler', '0005_alter_sunbak_crawl_datamodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunbak_crawl_datamodel',
            name='siteName',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
