# Generated by Django 4.2 on 2023-05-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbak_crawler', '0006_sunbak_crawl_datamodel_sitename'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunbak_crawl_datamodel',
            name='price_int',
            field=models.IntegerField(default=0),
        ),
    ]
