# Generated by Django 4.2 on 2023-05-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunbak_crawler', '0008_sunbak_crawl_datamodel_articleno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sunbak_crawl_datamodel',
            name='articleNo',
        ),
    ]
