# Generated by Django 4.2 on 2023-05-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbak_crawler', '0009_remove_sunbak_crawl_datamodel_articleno'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunbak_crawl_datamodel',
            name='regNumber',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sunbak_crawl_datamodel',
            name='price_int',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
