# Generated by Django 4.2 on 2023-05-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbak_crawler', '0010_sunbak_crawl_datamodel_regnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunbak_crawl_datamodel',
            name='detailURL',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='sunbak_crawl_datamodel',
            unique_together={('siteName', 'regNumber')},
        ),
    ]
