# Generated by Django 4.2 on 2023-05-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbak_crawler', '0012_sunbak_crawl_datamodel_boardurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunbak_crawl_datamodel',
            name='thumb_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
