# Generated by Django 4.2 on 2023-05-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbak_crawler', '0013_sunbak_crawl_datamodel_thumb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunbak_crawl_datamodel',
            name='tons',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sunbak_crawl_datamodel',
            name='thumb_image',
            field=models.ImageField(null=True, upload_to='thumbs/'),
        ),
    ]
