# Generated by Django 4.2 on 2023-08-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbak_crawler', '0017_sunbak_crawl_datamodel_modelyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunbak_crawl_datamodel',
            name='salesLocation',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
